# Generated by Django 5.2.17 on 2026-09-24 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='location_verified',
            field=models.BooleanField(default=False, help_text="True if this location came from the visitor's own device GPS (they tapped 'Allow'), not just guessed from their IP address."),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session_key'], name='analytics_p_session_0d9222_idx'),
        ),
    ]
