# Generated by Django 5.2.17 on 2026-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Why the correct answer is correct - shown to students after they submit a test'),
        ),
    ]
