# Generated by Django 5.2.17 on 2026-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='slice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
