# Generated by Django 5.2.17 on 2026-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.CharField(choices=[('fox', 'Fox'), ('owl', 'Owl'), ('cat', 'Cat'), ('panda', 'Panda'), ('lion', 'Lion'), ('koala', 'Koala'), ('tiger', 'Tiger'), ('rabbit', 'Rabbit')], default='fox', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
