# Generated by Django 5.2.17 on 2026-08-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_avatar_studentprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Fox, Owl - shown as a label under the avatar', max_length=50)),
                ('emoji', models.CharField(blank=True, help_text='Optional fallback emoji, e.g. 🦊 (used only if no image is uploaded)', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a profile picture image (preferred over emoji)', null=True, upload_to='avatars/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.avatar'),
        ),
    ]
