# Generated by Django 5.2.17 on 2026-09-02 15:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avatar_alter_studentprofile_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Uploader (Notes upload access only)',
                'verbose_name_plural': 'Uploaders (Notes upload access only)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='emoji',
            field=models.CharField(help_text='The emoji shown as the avatar, e.g. 🦊', max_length=10),
        ),
    ]
