# Generated by Django 5.2.17 on 2026-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uploaderaccount_remove_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, help_text='Preferred - a real avatar picture', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='emoji',
            field=models.CharField(blank=True, help_text='Fallback shown only if no image is uploaded, e.g. 🦊', max_length=10),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(help_text='For your own reference in the admin only - students never see this', max_length=50),
        ),
    ]
