# Generated by Django 5.2.17 on 2026-09-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='doubt_limit_per_day',
            field=models.PositiveIntegerField(default=10, help_text='How many AI Doubt Solver questions this student can ask per day. Raise it here if they ask for more.'),
        ),
    ]
