# Generated by Django 5.2.17 on 2026-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_doubt_limit_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='daily_goal',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
