# Generated by Django 5.2.17 on 2026-08-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(choices=[(9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])),
                ('year', models.PositiveIntegerField()),
                ('set_label', models.CharField(blank=True, help_text='Optional, e.g. "Set 1" if multiple sets exist', max_length=50)),
                ('pdf_file', models.FileField(upload_to='pyq_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyq_papers', to='notes.subject')),
            ],
            options={
                'ordering': ['-year', 'subject__name'],
            },
        ),
    ]
