# Generated by Django 5.2.17 on 2026-09-18 09:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_pyqpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='notes_pdfs/'),
        ),
        migrations.AlterField(
            model_name='pyqpaper',
            name='pdf_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pyq_papers/'),
        ),
    ]
