# Generated by Django 5.2.17 on 2026-09-19 11:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_pdf_file_alter_pyqpaper_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='notes_pdfs/'),
        ),
        migrations.AlterField(
            model_name='pyqpaper',
            name='pdf_file',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pyq_papers/'),
        ),
    ]
