# Generated by Django 5.2.17 on 2026-09-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_pdf_file_alter_pyqpaper_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Chapter Notes'), ('subjective', 'Subjective Questions')], default='notes', max_length=20),
        ),
    ]
