# Chapter lists for the newly added subjects: Hindi, English, Grammar,
# Vyakaran, IT - across CBSE Class 9, 10, 11, 12.
#
# NOTE: These follow the commonly-used NCERT textbooks (Kshitij/Kritika,
# Aroh/Vitan for Hindi; Beehive/Moments, First Flight/Footprints,
# Hornbill/Snapshots, Flamingo/Vistas for English). CBSE has been
# rationalising some textbooks (e.g. Class 9 Hindi is moving to a new
# combined book called "Ganga" in some schools) - double check against
# your own school's textbook and edit this list if titles differ.
#
# "Grammar" (English grammar) and "Vyakaran" (Hindi grammar) are treated
# as their own subjects here (as requested), with topic-wise chapters
# instead of story/poem chapters.

NEW_SUBJECTS_SYLLABUS = {
    9: {
        "Hindi": [
            "Dukh Ka Adhikar",
            "Everest: Meri Shikhar Yatra",
            "Tum Kab Jaoge, Atithi",
            "Vaigyanik Chetna Ke Vahak: Chandrashekhar Venkat Raman",
            "Dhwani (Kavita)",
            "Kaidi Aur Kokila (Kavita)",
            "Gramya Jeevan Ke Aadhar (Dohe)",
            "Ek Phool Ki Chah (Kavita)",
            "Is Jal Pralay Mein",
            "Mere Sang Ki Auratein",
        ],
        "English": [
            "The Fun They Had",
            "The Sound of Music",
            "The Little Girl",
            "A Truly Beautiful Mind",
            "The Snake and the Mirror",
            "My Childhood",
            "Reach for the Top",
            "Kathmandu",
            "The Lost Child",
            "The Adventures of Toto",
            "Iswaran the Storyteller",
            "In the Kingdom of Fools",
        ],
        "Grammar": [
            "Tenses",
            "Modals",
            "Subject-Verb Agreement",
            "Determiners",
            "Prepositions",
            "Reported Speech (Direct-Indirect)",
            "Active and Passive Voice",
            "Editing and Omission",
            "Gap Filling",
        ],
        "Vyakaran": [
            "Sandhi",
            "Samas",
            "Upsarg Aur Pratyay",
            "Paryayvachi Shabd",
            "Vilom Shabd",
            "Anekarthi Shabd",
            "Muhavare Aur Lokoktiyan",
            "Shabd Shuddhi",
            "Vakya Shuddhi",
            "Anuched Lekhan",
        ],
        "IT": [
            "Communication Skills",
            "Self-Management Skills",
            "ICT Skills",
            "Entrepreneurial Skills",
            "Green Skills",
            "Digital Documentation (Word Processing)",
            "Electronic Spreadsheet - Basics",
            "Database Management System - Basics",
        ],
    },
    10: {
        "Hindi": [
            "Surdas Ke Pad",
            "Ram-Lakshman-Parshuram Samvad",
            "Savaiya Aur Kavitt",
            "Aatmakathya (Kavita)",
            "Manushyata (Kavita)",
            "Netaji Ka Chashma",
            "Balgobin Bhagat",
            "Lakhnavi Andaz",
            "Ek Kahani Yeh Bhi",
            "Girgit",
            "Maata Ka Aanchal",
            "Sana Sana Haath Jodi",
        ],
        "English": [
            "A Letter to God",
            "Nelson Mandela: Long Walk to Freedom",
            "Two Stories about Flying",
            "From the Diary of Anne Frank",
            "Glimpses of India",
            "Mijbil the Otter",
            "Madam Rides the Bus",
            "The Sermon at Benares",
            "The Proposal",
            "A Triumph of Surgery",
            "The Thief's Story",
            "The Midnight Visitor",
            "Footprints without Feet",
            "The Making of a Scientist",
            "The Necklace",
            "Bholi",
        ],
        "Grammar": [
            "Tenses (Advanced)",
            "Modals",
            "Reported Speech",
            "Active and Passive Voice",
            "Clauses: Noun, Adjective, Adverb",
            "Determiners",
            "Prepositions",
            "Editing and Omission",
            "Gap Filling / Cloze Test",
        ],
        "Vyakaran": [
            "Sandhi Aur Uske Bhed",
            "Samas Aur Uske Bhed",
            "Alankar",
            "Ras",
            "Chhand",
            "Vachya (Kriya)",
            "Pad Parichay",
            "Vakya Vishleshan (Rachna Ke Aadhar Par)",
            "Muhavare Aur Lokoktiyan",
            "Patra Lekhan",
        ],
        "IT": [
            "Digital Documentation (Advanced)",
            "Electronic Spreadsheet (Advanced)",
            "Database Management System",
            "Web Applications and Security",
            "Communication Skills II",
            "Entrepreneurial Skills II",
        ],
    },
    11: {
        "Hindi": [
            "Namak (Kahani)",
            "Bazaar Darshan",
            "Kartoos",
            "Joojh",
            "Khanabadosh (Kavita)",
            "Ghar Ki Yaad (Kavita)",
            "Sillan",
            "Rajasthan Ki Rajat Boondein",
        ],
        "English": [
            "The Portrait of a Lady",
            "We're Not Afraid to Die... If We Can All Be Together",
            "Discovering Tut: The Saga Continues",
            "Landscape of the Soul",
            "The Ailing Planet: The Green Movement's Role",
            "The Browning Version",
            "The Adventure",
            "Silk Road",
            "The Summer of the Beautiful White Horse",
            "The Address",
            "Ranga's Marriage",
            "Albert Einstein at School",
            "Mother's Day",
            "The Tale of Melon City",
        ],
        "Grammar": [
            "Tenses and Modals (Advanced)",
            "Narration (Direct-Indirect Speech)",
            "Voice: Active and Passive",
            "Clauses and Sentence Transformation",
            "Vocabulary: Synonyms, Antonyms, One-word Substitution",
            "Editing and Omission",
            "Note Making and Summarising",
        ],
        "Vyakaran": [
            "Shabd Shakti",
            "Ras",
            "Chhand",
            "Alankar (Advanced)",
            "Kaarak",
            "Samas (Advanced)",
            "Vakya Rachna",
            "Anuchhed Aur Nibandh Lekhan",
        ],
        "IT": [
            "Web Application and Security",
            "Networking and Internet",
            "Cyber Security",
            "Digital Documentation Using Advanced Word Processor",
        ],
    },
    12: {
        "Hindi": [
            "Aatmaparichay (Kavita)",
            "Ek Geet (Kavita)",
            "Patang (Kavita)",
            "Ushaa (Kavita)",
            "Bat Seedhi Thi Par (Kavita)",
            "Kartoos (Kahani)",
            "Silver Wedding",
            "Joojh",
        ],
        "English": [
            "The Last Lesson",
            "Lost Spring",
            "Deep Water",
            "The Rattrap",
            "Indigo",
            "Poets and Pancakes",
            "The Interview",
            "Going Places",
            "The Third Level",
            "The Tiger King",
            "Journey to the End of the Earth",
            "The Enemy",
            "Should Wizard Hit Mommy",
            "On the Face of It",
            "Evans Tries an O-level",
            "Memories of Childhood",
        ],
        "Grammar": [
            "Advanced Tenses and Modals",
            "Narration and Voice (Advanced)",
            "Transformation of Sentences",
            "Vocabulary and One-word Substitution",
            "Note Making and Summarising",
            "Editing and Omission (Board Pattern)",
        ],
        "Vyakaran": [
            "Ras (Advanced)",
            "Alankar (Advanced)",
            "Samas Aur Sandhi (Revision)",
            "Kaarak (Advanced)",
            "Pad Parichay (Advanced)",
            "Nibandh Lekhan",
        ],
        "IT": [
            "Data Handling Using Spreadsheet - Advanced",
            "Maintaining Database",
            "Networking and Internet - Advanced",
            "Cyber Security - Advanced",
            "Web Application Development Basics",
        ],
    },
}
